### ISSUE TITLE
Google Calendar - Inaccurate Dates

### ISSUE THREAD

**Issue by joshuaj1397** [ynigoreyes/TTUACM_Website#73]
When an event spans several days the website will say the date of the event is before the first actual day of the event on Google Calendar. It also does this sometimes when there is an event that spans the entire day.

**Comment by ynigoreyes** [comment]
@joshuaj1397 Which ones exactly are the events that are inaccurate?

**Comment by ynigoreyes** [comment]
Fixed the problem, expect the changes to go live in 10 minutes
